/**
 * feature-builder.ts
 *
 * Generates Karate DSL .feature files from the canonical APIModel.
 *
 * Output structure (grouped by tag):
 *   outputDir/
 *     orders/
 *       createOrder.feature
 *       getOrders.feature
 *     users/
 *       getUser.feature
 *     common/
 *       auth.feature
 *     karate-config.js
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import type {
  APIModel,
  APIEndpoint,
  SecurityRequirement,
  JSONSchemaDefinition,
} from "@fullstack-test-suite/shared";
import {
  generateExampleValue,
  generateExampleObject,
} from "@fullstack-test-suite/shared";
import {
  toKarateMatcher,
  buildSchemaValidation,
  generateNegativeCases,
} from "./schema-matcher.js";

export interface GenerationResult {
  filesWritten: string[];
  summary: string;
}

/**
 * Generate all Karate feature files from an APIModel.
 */
export async function generateFeatureFiles(
  apiModel: APIModel,
  outputDir: string,
  groupBy: "tag" | "path" = "tag"
): Promise<GenerationResult> {
  const filesWritten: string[] = [];

  // Group endpoints
  const groups = groupEndpoints(apiModel.endpoints, groupBy);

  for (const [groupName, endpoints] of Object.entries(groups)) {
    for (const endpoint of endpoints) {
      const featureContent = buildFeatureFile(endpoint, apiModel);
      const fileName = buildFileName(endpoint);
      const filePath = join(outputDir, groupName, fileName);

      await ensureDir(dirname(filePath));
      await writeFile(filePath, featureContent, "utf-8");
      filesWritten.push(filePath);
    }
  }

  // Generate auth feature if security schemes exist
  const hasAuth = apiModel.endpoints.some(
    (ep) => ep.security && ep.security.length > 0
  );
  if (hasAuth) {
    const authPath = join(outputDir, "common", "auth.feature");
    await ensureDir(dirname(authPath));
    const firstSecurity = apiModel.endpoints.find((ep) => ep.security)?. security?.[0];
    await writeFile(authPath, buildAuthFeature(firstSecurity), "utf-8");
    filesWritten.push(authPath);
  }

  return {
    filesWritten,
    summary: `Generated ${filesWritten.length} Karate feature files for ${apiModel.endpoints.length} endpoints`,
  };
}

/**
 * Generate karate-config.js with environment support.
 */
export async function generateKarateConfig(
  apiModel: APIModel,
  outputDir: string,
  environments?: Record<string, string>
): Promise<string> {
  const envs = environments ?? { local: apiModel.baseUrl };
  const envEntries = Object.entries(envs)
    .map(([env, url]) => `    case '${env}': config.baseUrl = '${url}'; break;`)
    .join("\n");

  const content = `// karate-config.js — AUTO-GENERATED by fullstack-test-suite-mcp
function fn() {
  var env = karate.env || 'local';
  var config = {
    baseUrl: '${apiModel.baseUrl}'
  };

  switch (env) {
${envEntries}
    default: karate.log('Unknown environment:', env);
  }

  karate.configure('connectTimeout', 10000);
  karate.configure('readTimeout', 10000);

  return config;
}
`;

  const filePath = join(outputDir, "karate-config.js");
  await ensureDir(outputDir);
  await writeFile(filePath, content, "utf-8");
  return filePath;
}

// ─── Internal builders ─────────────────────────

function groupEndpoints(
  endpoints: APIEndpoint[],
  groupBy: "tag" | "path"
): Record<string, APIEndpoint[]> {
  const groups: Record<string, APIEndpoint[]> = {};

  for (const ep of endpoints) {
    let key: string;
    if (groupBy === "tag") {
      key = ep.tags.length > 0 ? sanitizeName(ep.tags[0]) : "general";
    } else {
      // Group by first path segment: /api/orders/{id} → orders
      const segments = ep.path.split("/").filter(Boolean);
      key = segments.length > 1 ? sanitizeName(segments[1]) : sanitizeName(segments[0] ?? "general");
    }

    if (!groups[key]) groups[key] = [];
    groups[key].push(ep);
  }

  return groups;
}

function buildFileName(endpoint: APIEndpoint): string {
  if (endpoint.operationId) {
    return `${sanitizeName(endpoint.operationId)}.feature`;
  }
  // Fallback: method + path → GET /api/orders → get-orders.feature
  const pathPart = endpoint.path
    .replace(/[{}]/g, "")
    .split("/")
    .filter(Boolean)
    .join("-");
  return `${endpoint.method.toLowerCase()}-${pathPart}.feature`;
}

function buildFeatureFile(
  endpoint: APIEndpoint,
  apiModel: APIModel
): string {
  const lines: string[] = [];
  const featureName = endpoint.summary || `${endpoint.method} ${endpoint.path}`;

  lines.push(`# ${buildFileName(endpoint)} — AUTO-GENERATED by fullstack-test-suite-mcp`);
  lines.push(`Feature: ${featureName}`);
  lines.push("");

  // Background
  lines.push("  Background:");
  lines.push("    * url baseUrl");

  if (endpoint.security && endpoint.security.length > 0) {
    lines.push("    * def auth = call read('classpath:common/auth.feature')");
    lines.push("    * header Authorization = 'Bearer ' + auth.token");
  }

  lines.push("");

  // Happy path scenario
  lines.push(...buildHappyPathScenario(endpoint, apiModel));

  // Negative test scenarios for POST/PUT/PATCH with request bodies
  if (
    endpoint.requestBody &&
    ["POST", "PUT", "PATCH"].includes(endpoint.method)
  ) {
    const negCases = generateNegativeCases(endpoint.requestBody.schema);
    if (negCases.length > 0) {
      lines.push("");
      lines.push(...buildNegativeScenarios(endpoint, negCases));
    }
  }

  // 404 scenario for endpoints with path parameters
  const pathParams = endpoint.parameters.filter((p) => p.in === "path");
  if (pathParams.length > 0) {
    lines.push("");
    lines.push(...buildNotFoundScenario(endpoint));
  }

  lines.push("");
  return lines.join("\n");
}

function buildHappyPathScenario(
  endpoint: APIEndpoint,
  _apiModel: APIModel
): string[] {
  const lines: string[] = [];
  const successCode = findSuccessCode(endpoint);

  lines.push(`  Scenario: ${endpoint.method} ${endpoint.path} - Happy path (${successCode})`);
  lines.push(`    Given path '${endpoint.path}'`);

  // Path parameters
  for (const param of endpoint.parameters.filter((p) => p.in === "path")) {
    const example = param.example ?? generateExampleValue(param.schema);
    lines.push(`    * def ${param.name} = '${example}'`);
    // Replace path placeholder
    lines[lines.length - 2] = lines[lines.length - 2].replace(
      `{${param.name}}`,
      `' + ${param.name} + '`
    );
  }

  // Query parameters
  const queryParams = endpoint.parameters.filter(
    (p) => p.in === "query" && p.required
  );
  if (queryParams.length > 0) {
    for (const param of queryParams) {
      const example = param.example ?? generateExampleValue(param.schema);
      lines.push(`    And param ${param.name} = '${example}'`);
    }
  }

  // Request body
  if (endpoint.requestBody) {
    const example = endpoint.requestBody.example ??
      generateExampleObject(endpoint.requestBody.schema);
    lines.push("    And request");
    lines.push('      """');
    lines.push(
      JSON.stringify(example, null, 6)
        .split("\n")
        .map((l) => `      ${l}`)
        .join("\n")
    );
    lines.push('      """');
  }

  lines.push(`    When method ${endpoint.method}`);
  lines.push(`    Then status ${successCode}`);

  // Response assertions
  const successResponse = endpoint.responses[successCode] ?? endpoint.responses["200"];
  if (successResponse?.schema) {
    if (successResponse.schema.type === "array") {
      lines.push("    And match response == '#array'");
    } else if (successResponse.schema.type === "object") {
      // Assert key fields are present
      if (successResponse.schema.properties) {
        for (const [key, propSchema] of Object.entries(
          successResponse.schema.properties
        )) {
          lines.push(
            `    And match response.${key} == '${toKarateMatcher(propSchema)}'`
          );
        }
      }
    }
  }

  return lines;
}

function buildNegativeScenarios(
  endpoint: APIEndpoint,
  cases: Array<{ field: string; invalidValue: string; reason: string }>
): string[] {
  const lines: string[] = [];

  lines.push(`  Scenario Outline: ${endpoint.method} ${endpoint.path} - Validation error (400)`);
  lines.push(`    Given path '${endpoint.path}'`);
  lines.push("    And request { <field>: <invalidValue> }");
  lines.push(`    When method ${endpoint.method}`);
  lines.push("    Then status 400");
  lines.push("");
  lines.push("    Examples:");
  lines.push("      | field          | invalidValue | reason                    |");

  for (const c of cases) {
    const paddedField = c.field.padEnd(14);
    const paddedValue = c.invalidValue.padEnd(12);
    const paddedReason = c.reason;
    lines.push(`      | ${paddedField} | ${paddedValue} | ${paddedReason} |`);
  }

  return lines;
}

function buildNotFoundScenario(endpoint: APIEndpoint): string[] {
  return [
    `  Scenario: ${endpoint.method} ${endpoint.path} - Not found (404)`,
    `    Given path '${endpoint.path.replace(/\{[^}]+\}/g, "nonexistent-id-999")}'`,
    `    When method ${endpoint.method}`,
    "    Then status 404",
  ];
}

function buildAuthFeature(
  security: SecurityRequirement | undefined
): string {
  const type = security?.type ?? "http";
  const scheme = security?.scheme ?? "bearer";

  return `# auth.feature — AUTO-GENERATED by fullstack-test-suite-mcp
# Reusable authentication flow.
# TODO: Replace placeholder credentials with actual test account values.

Feature: Authentication

  Scenario: Get auth token
    * def token = 'TODO_REPLACE_WITH_REAL_TOKEN'

    # For a real implementation, uncomment and configure:
    # Given url baseUrl + '/auth/login'
    # And request { username: 'testuser', password: 'testpass' }
    # When method POST
    # Then status 200
    # * def token = response.token

    # Auth type detected from spec: ${type} / ${scheme}
`;
}

// ─── Utility helpers ───────────────────────────

function findSuccessCode(endpoint: APIEndpoint): string {
  const codes = Object.keys(endpoint.responses);
  if (codes.includes("201") && ["POST", "PUT"].includes(endpoint.method))
    return "201";
  if (codes.includes("200")) return "200";
  if (codes.includes("204") && endpoint.method === "DELETE") return "204";
  return codes.find((c) => c.startsWith("2")) ?? "200";
}

function sanitizeName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}



async function ensureDir(dir: string): Promise<void> {
  await mkdir(dir, { recursive: true });
}
